### PR TITLE
Reordering releases to get the right latest release

### PR DESCRIPTION
**Pull request by ahcorde**
This PR is related with this issue https://github.com/ignitionrobotics/docs/issues/4

I tested this locally

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by maryaB-osr** [comment]
Can you confirm that it doesn't change the order that the releases are listed under "Releases" on [the front docs page](https://ignitionrobotics.org/docs)?

**Comment by ahcorde** [comment]
It does change it.

**Comment by ahcorde** [comment]
If this is relevant I can change the backend to use the right order

**Comment by ahcorde** [comment]
This was fixed in the backend

**Pull request closed without merging**
